/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.controlador.CreacionArchivo;
import com.controlador.Secuencia;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Carlos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        //lblPictureF1.setSize(50,40);
        establecertamanio("./salidaGUI/img_defecto.png",lblPictureF1);
        jTabbedPane1.getModel().getSelectedIndex();
        /*Component object =jTabbedPane1.getComponent(0);
        System.out.println("A:"+object.getAccessibleContext().getAccessibleName());*/
        
        System.out.println(jTabbedPane1.getTabCount());
        
        /*for (Component object : jTabbedPane1.getComponents()) {
            object.setEnabled(false);
        }*/
    }

    public void establecertamanio(String ruta,JLabel lblImagen)
    {
        //lblPictureF1.setSize(500, 400);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(ruta).getImage().getScaledInstance(800, 600, Image.SCALE_DEFAULT));
        imageIcon.getImage().flush();
        lblImagen.setIcon(imageIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        btnGraficar = new javax.swing.JButton();
        cmbOperaciones = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFuncion2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFactor = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        lblPictureF1 = new javax.swing.JLabel();
        lblPictureF2 = new javax.swing.JLabel();
        lblPictureF3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese función x(n):");

        btnGraficar.setText("Calcular");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suma", "Resta", "Multiplicación", "Atenuación-Amplificación", "Desplazamiento", "Reflejo", "Diezmación", "Interpolación a cero", "Interpolación a escalón", "Interpolación lineal" }));

        jLabel2.setText("seleccione operacion");

        jLabel3.setText("Ingrese funcion x2(n)");

        jLabel4.setText("Formato de datos: puede ingresar la secuencia separada por comas, indicando el origen de los datos con la letra O seguida al valor correspondiente al origen");

        jLabel5.setText("Ingrese el valor");

        txtFactor.setText("0");

        lblPictureF1.setMaximumSize(new java.awt.Dimension(800, 600));
        lblPictureF1.setMinimumSize(new java.awt.Dimension(50, 40));
        lblPictureF1.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.addTab("Secuencia1", lblPictureF1);
        lblPictureF1.getAccessibleContext().setAccessibleDescription("");

        lblPictureF2.setMaximumSize(new java.awt.Dimension(800, 600));
        lblPictureF2.setMinimumSize(new java.awt.Dimension(50, 40));
        lblPictureF2.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.addTab("Secuencia2", lblPictureF2);

        lblPictureF3.setMaximumSize(new java.awt.Dimension(800, 600));
        lblPictureF3.setMinimumSize(new java.awt.Dimension(50, 40));
        lblPictureF3.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.addTab("Resultado", lblPictureF3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGraficar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFuncion2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txtFactor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFuncion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(btnGraficar))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        String seleccionado = cmbOperaciones.getSelectedItem().toString();
        System.out.println("seleccionado" + seleccionado);
        String funcion1 = txtFuncion.getText();
        Secuencia secuencia2 = null;
        if(!txtFuncion2.getText().equals(""))
        {
            String funcion2 = txtFuncion2.getText();
            secuencia2 = new Secuencia(funcion2);
        }

        Secuencia secuencia1 = new Secuencia(funcion1);
        //hasta aqui
//        Secuencia.centrarOrigen(secuencia1, secuencia2);
        switch (seleccionado) {
            //OPERACIONES QUE REQUIEREN DE DOS SECUENCIAS
            case "Suma"://ya esta
                jTabbedPane1.setEnabledAt(1, true);
                Secuencia.centrarOrigen(secuencia1, secuencia2);              
                CreacionArchivo caSuma = new CreacionArchivo(secuencia1, secuencia2, "suma");
                //guardar resultado //futuro
                //mostrar a usuario
                break;
            case "Resta"://ya esta
                jTabbedPane1.setEnabledAt(1, true);
                Secuencia.centrarOrigen(secuencia1, secuencia2);              
                CreacionArchivo caResta = new CreacionArchivo(secuencia1, secuencia2, "resta");
                //guardar resultado
                //mostrar a usuario
                break;
            case "Multiplicación"://ya esta
                //ordenarOrigen
                jTabbedPane1.setEnabledAt(1, true);
                Secuencia.centrarOrigen(secuencia1, secuencia2);
                //Secuencia.centrarOrigen(secuencia1, secuencia2);
                //construir archivo
                CreacionArchivo caMultiplicacion = new CreacionArchivo(secuencia1, secuencia2, "multiplicacion");
                //ejecutar cmd
                //guardar resultado
                //mostrar a usuario
                break;
            //OPERACIONES QUE REQUIEREN SOLO UNA SECUENCIA
            case "Atenuación-Amplificación"://ya esta
                jTabbedPane1.setEnabledAt(1, false);
                //construir archivo
                CreacionArchivo caAmplificacion = new CreacionArchivo(secuencia1, "amplificacionatenuacion", txtFactor.getText());
                //ejecutar cmd
                //guardar resultado
                //mostrar a usuario
                break;
            case "Desplazamiento"://ya esta
                //construir archivo
                jTabbedPane1.setEnabledAt(1, false);
                CreacionArchivo caDesplazamiento = new CreacionArchivo(secuencia1, "desplazamiento", txtFactor.getText());
                //ejecutar cmd
                //guardar resultado
                //mostrar a usuario
                break;
            case "Reflejo"://ya esta
                jTabbedPane1.setEnabledAt(1, false);
                CreacionArchivo caReflejo = new CreacionArchivo(secuencia1, "reflejo", "no se usa");
                //ejecutar cmd
                //guardar resultado
                //mostrar a usuario
                break;
            case "Diezmación"://ya esta
                jTabbedPane1.setEnabledAt(1, false);
                CreacionArchivo caDiezmacion = new CreacionArchivo(secuencia1, "diezmacion", txtFactor.getText());
                //ejecutar cmd
                //guardar resultado
                //mostrar a usuario
                break;
            case "Interpolación a cero":
                jTabbedPane1.setEnabledAt(1, false);
                CreacionArchivo caInterpolacionACero = new CreacionArchivo(secuencia1, "interpolacionacero", txtFactor.getText());
                break;
            case "Interpolación a escalón":
                jTabbedPane1.setEnabledAt(1, false);
                CreacionArchivo caInterpolacionAEscalon = new CreacionArchivo(secuencia1, "interpolacionaescalon", txtFactor.getText());
                break;
            case "Interpolación lineal":
                jTabbedPane1.setEnabledAt(1, false);
                CreacionArchivo caInterpolacionLineal = new CreacionArchivo(secuencia1, "interpolacionlineal", txtFactor.getText());
                break;
            default:
                
                
                break;
                    
        }
        try {
            System.out.println("antes de sleep");
            Thread.sleep(4000);
            establecertamanio("./salidaGUI/imagen1.png",lblPictureF1);
            establecertamanio("./salidaGUI/imagen2.png",lblPictureF2);
            establecertamanio("./salidaGUI/imagen3.png",lblPictureF3);
            lblPictureF1.repaint();
            lblPictureF1.validate();
            actualizarPantalla();
            
            
            JOptionPane.showMessageDialog(null, "imagen actualizada");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGraficarActionPerformed

    public void actualizarPantalla(){
        SwingUtilities.updateComponentTreeUI(this);
        this.validateTree();
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPictureF1;
    private javax.swing.JLabel lblPictureF2;
    private javax.swing.JLabel lblPictureF3;
    private javax.swing.JTextField txtFactor;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtFuncion2;
    // End of variables declaration//GEN-END:variables
}
